services:
  app_ptm:
      restart: always
      container_name: app_ptm
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - 3000:3000
      environment:
        - MONGO_URI=mongodb://admin:password@db_ptm:27017
        - MONGO_DB_NAME=task_project
      depends_on:
        db_ptm:
          condition: service_healthy
  db_ptm:
    image: amd64/mongo:7.0.11
    restart: no
    container_name: db_ptm
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=task_project
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      retries: 3
    volumes:
      - mongodb_data:/data/db
      - ./docker/mongodb:/docker-entrypoint-initdb.d
  db_browser_ptm:
    image: mongo-express:latest
    restart: no
    container_name: db_browser_ptm
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=db_ptm
      - ME_CONFIG_MONGODB_PORT=27017
    ports:
      - 8081:8081
    depends_on:
      db_ptm:
        condition: service_healthy
  
volumes:
  mongodb_data: